[package]
name = "midyakis"
version = "0.0.1"
authors = ["Sinono3 <aldoacevedo@protonmail.com>"]
edition = "2018"

[target.'cfg(target_os = "windows")'.dependencies]
windows_bindings = { path = "windows_bindings" }
raw-window-handle = "0.3.3"

[target.'cfg(target_os = "windows")'.dev-dependencies]
winit = "0.24.0"