[package]
name = "souvlaki"
version = "0.1.0"
authors = ["Sinono3 <aldoacevedo@protonmail.com>"]
edition = "2018"
description = "A cross-platform media key and metadata handling library."
license = "MIT"

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle = "0.3.3"
windows = "0.3.1"

[target.'cfg(target_os = "windows")'.build-dependencies]
windows = "0.3.1"

[target.'cfg(target_os = "windows")'.dev-dependencies]
winit = "0.24.0"

[target.'cfg(target_os = "macos")'.dependencies]
block = "0.1.6"
cocoa = "0.24.0"
objc = "0.2.7"

[target.'cfg(target_os = "macos")'.dev-dependencies]
winit = "0.24.0"